version: "3.1"

services:
  server:
    image: investment-simulator-old
    build:
      context: .
    ports:
    - 4000:80
    networks:
      - investment-simulator-old-network

networks:
  investment-simulator-old-network:
    driver: bridge
